[package]
name = "patterns_rs"
version = "0.1.0"
authors = ["冬冬 李 <lsongzhi@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
downcast-rs = "1.1"
rand = "0.7"
once_cell = "1.3"